import { saveProduct } from '../lib/db';
import { Product } from '../lib/types';

const sampleProducts: Product[] = [
  {
    id: 'prod_gpu_1',
    telegramMessageId: 2001,
    channelName: '@canal_hardware',
    title: 'Placa de Vídeo RTX 4070 Super 12GB GDDR6X Asus Dual',
    price: 3899.9,
    originalPrice: 4799.9,
    discountPercent: 19,
    coupon: 'GPU150',
    url: 'https://www.kabum.com.br/produto/rtx4070super',
    store: 'KaBuM!',
    rawText: '🔥 MENOR PREÇO HISTÓRICO!\nPlaca de Vídeo RTX 4070 Super 12GB GDDR6X Asus Dual\nDe R$ 4.799,90 por R$ 3.899,90 à vista\n🎟️ Cupom: GPU150\nLink: https://www.kabum.com.br/produto/rtx4070super',
    createdAt: Date.now() - 1000 * 60 * 10,
  },
  {
    id: 'prod_monitor_1',
    telegramMessageId: 2002,
    channelName: '@canal_monitores',
    title: 'Monitor Gamer LG UltraGear 27" IPS 144Hz 1ms HDR10 FreeSync',
    price: 899.1,
    originalPrice: 1399.0,
    discountPercent: 36,
    coupon: 'MONITOR50',
    url: 'https://www.amazon.com.br/dp/B088LG27',
    store: 'Amazon',
    rawText: '🖥️ MONITOR EM PROMOÇÃO\nMonitor Gamer LG UltraGear 27" IPS 144Hz 1ms\nDe R$ 1.399,00 por R$ 899,10\nCupom: MONITOR50\nhttps://www.amazon.com.br/dp/B088LG27',
    createdAt: Date.now() - 1000 * 60 * 20,
  },
  {
    id: 'prod_oferta_1',
    telegramMessageId: 2003,
    channelName: '@canal_ofertas',
    title: 'Smart TV 55" 4K UHD Samsung Crystal 55DU8000',
    price: 2199.0,
    originalPrice: 2999.0,
    discountPercent: 27,
    coupon: 'TV100',
    url: 'https://www.magazineluiza.com.br/samsung55',
    store: 'Magalu',
    rawText: '📺 SMART TV 55 SAMSUNG\nSmart TV 55" 4K UHD Samsung Crystal 55DU8000\nDe R$ 2.999,00 por R$ 2.199,00\nCupom: TV100\nhttps://www.magazineluiza.com.br/samsung55',
    createdAt: Date.now() - 1000 * 60 * 35,
  },
  {
    id: 'prod_poison_1',
    telegramMessageId: 2004,
    channelName: '@canal_importados',
    title: 'Fone de Ouvido Bluetooth Anker Soundcore Life Q30 ANC',
    price: 269.9,
    originalPrice: 499.0,
    discountPercent: 46,
    coupon: 'POISON15',
    url: 'https://s.click.aliexpress.com/e/_soundcoreq30',
    store: 'AliExpress',
    rawText: '🎧 FONE COM CANCELAMENTO DE RUÍDO\nFone Anker Soundcore Life Q30 ANC\nDe R$ 499,00 por R$ 269,90\nCupom: POISON15\nhttps://s.click.aliexpress.com/e/_soundcoreq30',
    createdAt: Date.now() - 1000 * 60 * 50,
  },
  {
    id: 'prod_viajante_1',
    telegramMessageId: 2005,
    channelName: '@canal_achados',
    title: 'Mochila Impermeável Antifurto para Notebook 15.6" Bange',
    price: 119.9,
    originalPrice: 220.0,
    discountPercent: 45,
    coupon: 'VIAJANTE10',
    url: 'https://shope.ee/mochilabange',
    store: 'Shopee',
    rawText: '🎒 ACHADO SHOPEE\nMochila Impermeável Antifurto para Notebook 15.6"\nDe R$ 220,00 por R$ 119,90\nCupom: VIAJANTE10\nhttps://shope.ee/mochilabange',
    createdAt: Date.now() - 1000 * 60 * 70,
  },
  {
    id: 'prod_coruja_1',
    telegramMessageId: 2006,
    channelName: '@canal_casa',
    title: 'Fritadeira Sem Óleo Air Fryer Philco 4.2L Gourmet',
    price: 189.9,
    originalPrice: 329.9,
    discountPercent: 42,
    coupon: 'CORUJA20',
    url: 'https://mercadolivre.com.br/oferta/airfryer-philco',
    store: 'Mercado Livre',
    rawText: '🍟 AIR FRYER PHILCO\nFritadeira Sem Óleo Philco 4.2L\nDe R$ 329,90 por R$ 189,90\nCupom: CORUJA20\nhttps://mercadolivre.com.br/oferta/airfryer-philco',
    createdAt: Date.now() - 1000 * 60 * 85,
  },
  {
    id: 'prod_allan_1',
    telegramMessageId: 2007,
    channelName: '@canal_perifericos',
    title: 'Teclado Mecânico Gamer Redragon Kumara Switch Outemu Blue',
    price: 149.0,
    originalPrice: 249.0,
    discountPercent: 40,
    coupon: null,
    url: 'https://www.amazon.com.br/dp/B07ALLAN',
    store: 'Amazon',
    rawText: '⌨️ TECLADO MECÂNICO\nTeclado Mecânico Gamer Redragon Kumara\nDe R$ 249,00 por R$ 149,00 à vista\nhttps://www.amazon.com.br/dp/B07ALLAN',
    createdAt: Date.now() - 1000 * 60 * 110,
  },
  {
    id: 'prod_felipe_1',
    telegramMessageId: 2009,
    channelName: '@canal_armazenamento',
    title: 'SSD NVMe M.2 1TB Kingston NV2 PCIe 4.0 3500MB/s',
    price: 349.9,
    originalPrice: 489.0,
    discountPercent: 28,
    coupon: 'FELIPE20',
    url: 'https://mercadolivre.com.br/oferta/ssdkingston1tb',
    store: 'Mercado Livre',
    rawText: '💾 SSD NVME 1TB KINGSTON\nSSD NVMe M.2 1TB Kingston NV2\nDe R$ 489,00 por R$ 349,90\nCupom: FELIPE20\nhttps://mercadolivre.com.br/oferta/ssdkingston1tb',
    createdAt: Date.now() - 1000 * 60 * 170,
  },
  {
    id: 'prod_cupons_1',
    telegramMessageId: 2010,
    channelName: '@canal_cupons',
    title: 'Cupom Mercado Livre R$ 50 OFF em Todo o Site',
    price: 50.0,
    originalPrice: 50.0,
    discountPercent: 100,
    coupon: 'MELI50OFF',
    url: 'https://mercadolivre.com.br/cupons',
    store: 'Mercado Livre',
    rawText: '🎟️ Cupom Mercado Livre R$ 50 OFF em Todo o Site\nVálido para compras acima de R$ 200\nCupom: MELI50OFF\nhttps://mercadolivre.com.br/cupons',
    createdAt: Date.now() - 1000 * 60 * 10,
  },
  {
    id: 'prod_cupons_2',
    telegramMessageId: 2011,
    channelName: '@canal_cupons',
    title: 'Cupons Shopee Selecionados - Desconto de até R$ 40',
    price: 40.0,
    originalPrice: 40.0,
    discountPercent: 100,
    coupon: 'SHOPEE40',
    url: 'https://shopee.com.br/m/cupons-diarios',
    store: 'Shopee',
    rawText: '🎟️ Cupons Shopee Selecionados - Desconto de até R$ 40\nResgate os cupons na página oficial!\nCupom: SHOPEE40\nhttps://shopee.com.br/m/cupons-diarios',
    createdAt: Date.now() - 1000 * 60 * 5,
  },
];

console.log('[seed] Seeding sample products...');
for (const p of sampleProducts) {
  saveProduct(p);
}
console.log(`[seed] Saved ${sampleProducts.length} sample products to database.`);
